export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const INPUT_TEXT = 'INPUT_TEXT';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const CHANGE_VALUE = 'CHANGE_VALUE';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';